-- Describe the different types of join clauses supported in SQL.
-- An inner join selects matching values in the different tables. 
-- A left join returns all records from the left side and the matches from the right side. 
-- A right join returns all records from the right side and the matches from the left side. 
-- A full join returns all the records from both of the tables. 
-- A left join was used, assuming that the vendor table was the first table referenced in the code. 
